services:
  - type: web
    name: interview-scheduler
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask --app flaskr init-db
    startCommand: flask run --host=0.0.0.0 --port=$PORT