"""update interview and next steps

Revision ID: 457adc4bec08
Revises: 
Create Date: 2025-05-06 12:28:51.773263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457adc4bec08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('next_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_slot_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_slot_id'], ['interview_slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    with op.batch_alter_table('interview_slot', schema=None) as batch_op:
        batch_op.drop_column('next_steps')

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('interview_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_steps', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))

    op.drop_table('next_step')
    # ### end Alembic commands ###
