"""add meeting id

Revision ID: 709207b5ef56
Revises: 271717488a37
Create Date: 2025-04-17 19:53:42.610561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709207b5ef56'
down_revision = '271717488a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_slot', schema=None) as batch_op:
        batch_op.drop_column('meeting_id')

    # ### end Alembic commands ###
